"""Per-block BMC sub-agent (Phase 3 agentic core).

Each Osterwalder block is generated by its own ADK agent. The agent is given a
controlled, pre-retrieved set of NUMBERED filing excerpts (we keep retrieval in
our hands so citation→chunk mapping stays exact) and the NRE math tools. Its
job: write 2-4 cited bullets for the block using ONLY those excerpts, and call
``compute_*`` for ANY derived figure (growth %, margin, share) rather than
doing arithmetic itself.

This is the agentic upgrade over Phase 2 Lite's single LLM call: the block can
now verify/compute numbers deterministically mid-generation, so a bullet like
"revenue grew 7.4%" is NRE-checked, not model-guessed.

Evidence integrity: the agent does NOT get the retrieval tool — we control the
excerpt set + numbering, so ``[n]`` markers always map to real chunks.
"""

from __future__ import annotations

from src.agents.base import FINANCE_DOMAIN_RULES, PrismAgent
from src.agents.bmc.blocks import BMCBlockDef
from src.config import settings
from src.tools.nre_tools import NRE_TOOLS


def _instruction(block_def: BMCBlockDef) -> str:
    return f"""\
{FINANCE_DOMAIN_RULES}

YOU ARE generating ONE Business Model Canvas block: "{block_def.title}".
What this block captures: {block_def.focus}

You will receive a company name and NUMBERED filing excerpts. Rules:
- Use ONLY the provided excerpts. Do NOT use outside knowledge.
- Every bullet MUST cite the excerpt(s) it draws from with [n] markers.
- For ANY computed figure (growth %, CAGR, margin, ratio, % of revenue), call
  the matching ``compute_*`` tool with the raw numbers from the excerpts and
  use the tool's result — NEVER calculate in your head.
- If the excerpts have nothing relevant for this block, return an empty bullets
  list and set "evidence_missing": true. NEVER invent facts.
- 2 to 4 short bullets, one sentence each. No preamble.

Respond with STRICT JSON only (no markdown fences):
{{
  "bullets": ["...[1].", "..."],
  "key_insights": ["1-2 word tags"],
  "evidence_missing": false,
  "confidence": 0.0-1.0
}}
"""


def build_bmc_block_agent(block_def: BMCBlockDef) -> PrismAgent:
    """Construct the sub-agent for one BMC block.

    Tools = NRE only (math verification). Retrieval is done by the generator
    and passed in the prompt, so the agent can't drift off the controlled
    evidence set.
    """
    return PrismAgent(
        name=f"bmc_block_{block_def.block_id}",
        description=f"Generates the '{block_def.title}' BMC block from filing excerpts.",
        model_tier="quality",
        instruction=_instruction(block_def),
        tools=NRE_TOOLS.to_list(),
        max_iterations=settings.AGENT_MAX_ITERATIONS,
    )
